services:
  - type: web
    name: threat-detect-bommapala05
    env: docker
    plan: free
    envVars:
      - key: DB_PATH
        value: threats.db
      - key: OTX_API_KEY
        value: your_otx_key_here
